1.1 python 中boolean、float 和 int 分别表示什么？

答：boolean代表布尔型数据，float为浮点型数据，int为整数型数据

1.2 设计求1-2+3-4+5 ... 99的所有数的和

In [3]:
a = 1
sum = 0
for k in range(1,100):
    sum += a*k
    a = a*(-1)
print(sum)

50


1.3  将字符串 s="yoyo" 转换成列表

In [4]:
s = "yoyo"
print(list(s))

['y', 'o', 'y', 'o']


2.1 for i in range(1,100)[2::3][-10:]: 
            print i 

    理解这段代码，并说出它是如何取数的

答：在数字1至99之间，从序号为2的数开始每隔3个数取值，输出最后十个数

2.2 使用init 实例化时自动运行 分别计算单只股票最高价和收盘价两个时间点差值问题,可统一为one、two两个时间点,其最高价和收盘价赋值为 one(15,7) two(66,20)

In [5]:
class stock:
    def __init__(self,name,high,close):
        self.name = name
        self.high = high
        self.close = close
    def cal(self):
        return {self.name+'_dif':self.high-self.close}
stock_one = stock('one',15,7)
print(stock_one.cal())
stock_two = stock('two',66,20)
print(stock_two.cal())

{'one_dif': 8}
{'two_dif': 46}


3.1 如何查看列名、怎么对数据转置

答：查看列名使用DataFrame.columns()
    数据转置使用transpose()

3.2 读取data里的600029这只股票的DataFrame,将其收盘价转换成用Numpy的Array格式，并用talib计算10日EMA值，返回ndarray的最后五个值

In [12]:
import pandas as pd
import numpy as np
import talib as ta

In [16]:
stock = pd.read_excel('C://Users\风袖//Desktop//sz50.xlsx',sheet_name = '600029.XSHG', index_col = 'datetime')
close = np.array(stock.close)
print(type(close)) #查看close的类型
EMA = ta.EMA(close,timeperiod = 10)
print(EMA[-5:])

<class 'numpy.ndarray'>
[15.08227205 15.2564044  15.44433088 15.72172526 15.96322976]


3.3 读取sz50.xlsx的['600029.XSHG','600050.XSHG','601318.XSHG']的全数据做成Panel

In [17]:
import pandas as pd

In [20]:
stock_list = ['600029.XSHG','600050.XSHG','601318.XSHG']
stock_dic = {}
for k in stock_list:
    stock = pd.read_excel('C://Users\风袖//Desktop//sz50.xlsx',
                          sheet_name = k,
                          index_col = 'datetime'
                         )
    stock_dic[k] = stock.loc[:]
PN = pd.Panel(stock_dic)
print(PN)

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 215 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume


C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2961: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


3.4把Panel转成ndim为3的Numpy，然后用array的切片读取ndim为2的三只股票最近20天的收盘价

In [21]:
import numpy as np

In [24]:
stocknp = np.array(PN)
print(stocknp.shape)
print(stocknp[:,-20:,0])

(3, 215, 5)
[[ 13.85  13.82  13.83  14.11  14.25  14.39  15.1   15.15  15.22  14.97
   14.89  14.99  14.71  15.07  15.35  16.    16.04  16.29  16.97  17.05]
 [  8.53   8.56   8.62   8.88   9.25   9.24   9.43   9.25   9.02   9.15
    9.63   9.5    9.9    9.97   9.96   9.49   9.68   9.61   9.63   9.8 ]
 [134.83 134.56 137.5  143.18 143.48 144.15 143.61 143.65 144.35 143.36
  146.41 144.71 148.56 156.53 157.12 157.72 154.99 163.52 168.58 169.57]]


3.5 建立一个5*5的矩阵，值从0到24

In [25]:
import numpy as np

In [28]:
print(np.arange(25).reshape(5,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
